### ISSUE TITLE
code of tensorflow

### ISSUE THREAD

**Issue by MeiHuanshan** [yaoyao-liu/meta-transfer-learning#9]
Thank you for your excellent work in few-shot learning! I am very interset in your work.But when I run your code of tensorflow, I got an error 
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'exp_string'

I check the main.py, I not find flags.DEFINE_string('exp_string' ......)
the error was caused by code ?
my tewnsorflow version is 1.9.0 and I not sure it caused by version?

Thank you very much!

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

The variable `exp_string` is defined at <https://github.com/yaoyao-liu/meta-transfer-learning/blob/adf6351bfb9c1953ca280ab7eaabb15317cf711d/tensorflow/main.py#L74>. If you are using TensorFlow 1.3.0, it is able to create a variable like `exp_string` by directly assigning value to it instead of using the function `flags.DEFINE_string`. If you are using other versions of TensorFlow, you may need to change the code according to the official document.

If you have any other questions, feel free to add additional comments or create a new issue.

**Comment by MeiHuanshan** [comment]
> Thanks for your interest in our work.
> 
> The variable `exp_string` is defined at:
> 
> https://github.com/yaoyao-liu/meta-transfer-learning/blob/adf6351bfb9c1953ca280ab7eaabb15317cf711d/tensorflow/main.py#L74
> 
> 
> and
> https://github.com/yaoyao-liu/meta-transfer-learning/blob/adf6351bfb9c1953ca280ab7eaabb15317cf711d/tensorflow/main.py#L97
> 
> If you are using TensorFlow 1.3.0, it is able to create a variable like `exp_string` by directly assigning value to it instead of using the function `flags.DEFINE_string`. If you are using other versions of TensorFlow, you may need to change the code according to the official document.
> 
> If you have any other questions, feel free to add additional comments or create a new issue.

OK,Thank you very much for your reply! I have changed the code and run it succeed.

**Comment by changykang** [comment]
how do you change the code ,can you help me solve this problem? thank you

**Comment by yaoyao-liu** [comment]
I recommend you directly create a new environment with TensorFlow 1.3.0. It will solve this problem.
